name: Publish

on:
  push: {}
  pull_request: {}

env:
  IMAGE_NAME: "hstreamdb/hstream"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - builder_image: "hstreamdb/haskell:9.2"
            ld_image: "hstreamdb/logdevice:latest"
#            tag: "${GITHUB_REF#refs/*/}"
            tag: "latest"
          - builder_image: "hstreamdb/haskell:rqlite_9.2"
            ld_image: "hstreamdb/logdevice:rqlite"
#            tag: "rqlite_${GITHUB_REF#refs/*/}"
            tag: "rqlite_latest"
    steps:
      - run: |
          echo "${{ matrix.tag }}"
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

#      - name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v4
#        with:
#          images: ${ IMAGE_NAME }
#          tags:
#            - type=raw,value=${{ matrix.tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

#      - name: Cache Docker layers
#        uses: actions/cache@v3

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.tag }}
          build-args: |
            BUILDER_IMAGE=${{ matrix.builder_image }}
            LD_IMAGE=${{ matrix.ld_image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

#      - name: Docker build
#        run: |
#          docker build . -f docker/Dockerfile \
#            --build-arg BUILDER_IMAGE=${{ matrix.builder_image }} \
#            --build-arg LD_IMAGE=${{ matrix.ld_image }} \
#            -t ${IMAGE_NAME}:${{ matrix.tag }}
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Push image to dockerhub
#        run: docker push ${IMAGE_NAME}:${{ matrix.tag }}
#
#  trigger:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Trigger integration-tests ci
#        run: |
#          URL=https://api.github.com/repos/hstreamdb/integration-tests/dispatches
#          curl \
#            -X POST \
#            -H "Accept: application/vnd.github+json" \
#            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
#            -H "X-GitHub-Api-Version: 2022-11-28" \
#            $URL \
#              --data "{\"event_type\": \"image_updated\", \"client_payload\": { \"tag\": \"$TAG\", \"commit_sha\": \"$GITHUB_SHA\" }}"
#
#      - name: Trigger jepsen-tests ci
#        run: |
#          URL=https://api.github.com/repos/hstreamdb/jepsen.hstream/dispatches
#          curl \
#            -X POST \
#            -H "Accept: application/vnd.github+json" \
#            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
#            -H "X-GitHub-Api-Version: 2022-11-28" \
#            $URL \
#              --data "{\"event_type\": \"image_updated\", \"client_payload\": { \"tag\": \"$TAG\", \"commit_sha\": \"$GITHUB_SHA\" }}"
